argocd:
  namespace: argocd
  defaultTargetNamespace: apps

applications:
  - name: droneci
    gitPath: deployment/helm-charts/droneci-umbrella
    gitRepo: https://github.com/CrowdSalat/server-setup
