env:
  DRONE_SERVER_HOST: droneci.weyrich.dev
  DRONE_SERVER_PROTO: http
  DRONE_USER_FILTER: crowdsalat
  DRONE_USER_CREATE: username:crowdsalat,admin:true

extraSecretNamesForEnvFrom:
  - drone-secrets

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-dns-acme-ca
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: droneci.weyrich.dev
      servicePort: http
      paths:
        - /
  tls:
  - hosts:
    - droneci.weyrich.dev
    secretName: droneci-tls-secret
