apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true" 
  name: {{ include "spotidash.fullname" . }}
  namespace: apps
spec:
  encryptedData:
    SPOTIFY_CLIENT_ID_SECRET: {{ .Values.spotifiyOauth.encyptedClientSecret | quote }}
    SPOTIFY_CLIENT_ID: {{ .Values.spotifiyOauth.encyptedClientId | quote }}
